baseURL = "https://hiroshifujita.com/"
languageCode = "ja-jp"
defaultcontentlanguage="ja"
hasCJKLanguage=true
title = "HIROSHI FUJITA"
paginate=5
theme = "simple-and-fast"
googleAnalytics = "UA-164674809-1"
categories = ["blog", "page"]

[author]
  name = "hf-mush"
  mail = "fuchantoshu@gmail.com"

[social]
  facebook = "fujita.hiroshi.82"
  twitter = "shiropiritamma"
  github = "hf-mush"

[params]
  title = "HIROSHI FUJITA"
  description = "hiroshifujitaの活動や日々の記録をつづるブログ"
  images = ["https://hiroshifujita.com/img/hiroshifujita.jpg"]
  locale = "ja_JP"
  adsense = "ca-pub-4269106456957457"

[taxonomies]
  category = "categories"
