baseURL = "http://localhost:1313/"
languageCode = "ja-jp"
title = "HIROSHI FUJITA"
paginate=5
defaultcontentlanguage="ja"
theme = "simple-and-fast"
googleAnalytics = "U-XXXXXX-01"

[author]
  name = "hf-mush"
  github = "hf-mush"
  mail = "fuchantoshu@gmail.com"

[params]
  description = "hiroshifujitaの活動や日々の記録をつづるブログ"
  fbAppVersion = "v5.0"
  fbAppId = "00000000000"
  ogpImageURL = "http://localhost:1313/img/hiroshifujita.jpg"
