baseURL = "http://localhost:1313/"
languageCode = "ja-jp"
title = "HIROSHI FUJITA"
paginate=5

[author]
  name="hf-mush"

[params]
  analyticsCode = "U-XXXXXX-01"
  description = "hiroshifujitaの活動や日々の記録をつづるブログ"
  fbAppVersion = "v5.0"
  fbAppId = "00000000000"
  ogpImageURL = "http://localhost:1313/img/hiroshifujita.jpg"