baseURL = "http://localhost:1313/"
languageCode = "ja-jp"
defaultcontentlanguage="ja"
hasCJKLanguage=true
title = "HIROSHI FUJITA"
paginate=5
theme = "simple-and-fast"
googleAnalytics = "U-XXXXXX-01"
categories = ["blog", "page"]
uglyurls = true

[author]
  name = "hiroshifujita"
  mail = "fuchantoshu@gmail.com"

[social]
  facebook = "fujita.hiroshi.82"
  twitter = "shiropiritamma"
  github = "shuufujita"

[params]
  title = "HIROSHI FUJITA"
  description = "hiroshifujitaの活動や日々の記録をつづるブログ"
  images = ["http://localhost:1313/img/hiroshifujita.jpg"]
  locale = "ja_JP"
  adsense = "ca-pub-xxxxxxxxxxxxxxxxxxx"

[taxonomies]
  category = "categories"

[related]
  threshold = 80
  includeNewer = true
  toLower = true
  [[related.indices]]
    name = "keywords"
    weight = 20
  [[related.indices]]
    name = "date"
    weight = 30