baseURL = "https://hiroshifujita.com/"
languageCode = "ja-jp"
title = "HIROSHI FUJITA"
paginate=5
defaultcontentlanguage="ja"
theme = "simple-and-fast"
googleAnalytics = "UA-92967977-1"

[author]
  name = "hf-mush"
  github = "hf-mush"
  mail = "fuchantoshu@gmail.com"

[params]
  description = "hiroshifujitaの活動や日々の記録をつづるブログ"
  fbAppVersion = "v5.0"
  fbAppId = "833900463716082"
  ogpImageURL = "https://hiroshifujita.com/img/hiroshifujita.jpg"
