#!/bin/bash
SCRIPT_DIR="$(cd $(dirname $0) && pwd)"

files=$SCRIPT_DIR"/../static/img/*.jpg"

echo "execute start"
start_time=`date +%s`

echo "optimize img files."
jpegoptim --strip-all $files
echo "optimize success."

echo "convert jpg to webp start."
for filepath in $files; do
    converted=$(echo ${filepath:0:${#filepath}-4})
    cwebp $filepath -o $converted".webp"
done

echo "convert success."
end_time=`date +%s`
time=$((end_time - start_time))
echo "execute time : "$time" s"

exit 0