#!/bin/bash
SCRIPT_DIR="$(cd $(dirname $0) && pwd)"
cd $SCRIPT_DIR

if [ ! -e $SCRIPT_DIR/.env ]; then
  echo ".env no such file."
  exit 1
fi

. $SCRIPT_DIR/.env

if [ -z ${SSH_HOST} ]; then
  echo "does not set \$SSH_HOST"
  exit 1
fi

if [ -z ${REMOTE_TARGET} ]; then
  echo "does not set \$REMOTE_TARGET"
  exit 1
fi

cd $SCRIPT_DIR/..

echo "execute start"
start_time=`date +%s`

echo "build hugo resources."
hugo --config config.prod.toml --minify -D
echo "build success."

if [ ! -e public ]; then
  echo "public/ no such directory."
  exit 1
fi

echo "rsync resource to remote."
rsync --exclude='*.DS_Store' -r $SCRIPT_DIR/../public $SSH_HOST:$REMOTE_TARGET
echo "rsync success."

end_time=`date +%s`
time=$((end_time - start_time))
echo "execute time : "$time" s"

exit 0
