#!/bin/bash
SCRIPT_DIR="$(cd $(dirname $0) && pwd)"
cd $SCRIPT_DIR/..

echo "execute start"
start_time=`date +%s`

echo "optimize img files."
jpegoptim --strip-all static/img/*.jpg
echo "optimize success."

echo "convert img to webp from jpeg."
python scripts/convert_webp.py

echo "convert success."
end_time=`date +%s`
time=$((end_time - start_time))
echo "execute time : "$time" s"

exit 0
